### ISSUE TITLE
AttributeError: 'exceptions.UnicodeDecodeError' object has no attribute 'text'

### ISSUE THREAD

**Issue by dhi20** [vimeo/vimeo.php#164]
Hi,
Sorry if i'm missing something. I have tried to upload a video via vimeo.py on two different servers but without luck. I can amend existing video titles ect. but not upload. The reponse i get is as follows:

Traceback (most recent call last):
  File "/root/vimeo/test1.py", line 13, in <module>
    video_uri = v.upload('/home/fairlie/fairlie/webcam/fairlie/output.avi')
  File "/usr/local/lib/python2.7/dist-packages/vimeo/upload.py", line 72, in upload
    return self.__perform_tus_upload(filename, attempt)
  File "/usr/local/lib/python2.7/dist-packages/vimeo/upload.py", line 147, in __perform_tus_upload
    'Unexpected error when uploading through tus.'
  File "/usr/local/lib/python2.7/dist-packages/vimeo/exceptions.py", line 88, in __init__
    super(VideoUploadFailure, self).__init__(response, message)
  File "/usr/local/lib/python2.7/dist-packages/vimeo/exceptions.py", line 27, in __init__
    self.message = self.__get_message(response)
  File "/usr/local/lib/python2.7/dist-packages/vimeo/exceptions.py", line 20, in __get_message
    message = response.text
AttributeError: 'exceptions.UnicodeDecodeError' object has no attribute 'text'

Any guidance would be greatly appreciated.
Regards
Daniel

**Comment by amrutadotorg** [comment]
Hi I'm having the same issue. Do you have any solution for this error?
