### ISSUE TITLE
I implement the Vimeo API at localhost and its working fine but when I upload the code at c panel some SSL Connection errror occurs 

### ISSUE THREAD

**Issue by iambasitali** [vimeo/vimeo.php#199]

**Comment by iambasitali** [comment]
I implement the Vimeo API at localhost and it was working fine but when I upload the code at cpanel some SSL Connection errror occurs.

**Fatal error:** Uncaught exception 'Vimeo\Exceptions\VimeoRequestException' with message 'Unable to complete request.[SSL connect error]' in /var/www/vhosts/musicpax.com/httpdocs/launch_search/vimeo/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php:449 Stack trace: #0 /var/www/vhosts/musicpax.com/httpdocs/launch_search/vimeo/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php(133): Vimeo\Vimeo->_request('https://api.vim...', Array) #1 /var/www/vhosts/musicpax.com/httpdocs/launch_search/vimeo/index.php(51): Vimeo\Vimeo->request('/videos?query=t...', Array, 'GET') #2 /var/www/vhosts/musicpax.com/httpdocs/launch_search/vimeo/index.php(40): SearchVimeoVidoes('taki+taki') #3 {main} thrown in /var/www/vhosts/musicpax.com/httpdocs/launch_search/vimeo/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php on line 449

Please have a look on it and let me know how to fix that issue.
Thank You.

**Comment by tommypenner** [comment]
What version of TLS is configured on your end? Vimeo only accepts TLS 1.2 and newer connections, in compliance with [internet-wide](https://www.digicert.com/blog/depreciating-tls-1-0-and-1-1/) [security mandates](https://blog.pcisecuritystandards.org/are-you-ready-for-30-june-2018-sayin-goodbye-to-ssl-early-tls).

**Comment by iambasitali** [comment]
Hi @tommypenner  I am using TLS 1.1 as shown in the below screenshot
https://www.screencast.com/t/hrArLQK6sq1

**Comment by tommypenner** [comment]
Check your configuration and verify that you're connecting to Vimeo using a TLS 1.2 connection, that should resolve the SSL error.

**Comment by iambasitali** [comment]
Hi @tommypenner I did not found configuration 
How to connect Vimeo with TLS 1.2?
I am totally stuck here to find out the solution.

**Comment by iambasitali** [comment]
@tommypenner  I checked again that we are using TLS 1.2.
is there somthing else issue??
Is there need to any command from command prompt.

**Comment by czmole** [comment]
Probabbly not the wisest safest way but on older PHP version 5.6 we need to stick for the moment, to force the TLS 1.2 usage you can use an option for curl _CURLOPT_SSLVERSION => 6_ 

A small script to check for your version of TLS when attempting to use 1.2 https://gist.github.com/czmole/67f43af15d14c2d604cde5e178c57d3f

**Comment by czmole** [comment]
Details of CURLOP_SSLVERSION can be checked here https://curl.haxx.se/libcurl/c/CURLOPT_SSLVERSION.html

**Comment by eddster37** [comment]
@iambasitali my company had the same issue, and ours had to do with the firewall.
