### ISSUE TITLE
Unable to create resource

### ISSUE THREAD

**Issue by kailasb** [vimeo/vimeo.php#282]
@erunion
I'm facing the issue while upload the video.
it's working fine locally but it create the URL with **https://asia-files.tus.vimeo.com/files/vimeo-prod-src-tus-asia/3db9d46ef63cdfb01112798c352b05de**

but when I upload the video from server it generating URL like **https://europe-files.tus.vimeo.com/files/vimeo-prod-src-tus-eu/62566c38373b68318218e1f2b8239eb5** this and getting error **"Unable to create resource"**

can you help on this?

**Comment by erunion** [comment]
@kailasb I no longer work at Vimeo so you'll want to reach out to their support team. Sorry!

**Comment by kailasb** [comment]
do you have any idea I've also upgrade the vimeo plugin to 3.0.6 & ankitpokhrel/tus-php: 1.2.1

**Comment by erunion** [comment]
Sorry I can't help you, I haven't worked on or with the product in almost two years. You should reach out to their support and they'll be able to help you out.

**Comment by charlietango** [comment]
@kailasb did you find any solution? I'm facing the same situation. It used to work just fine but a few weeks ago stopped working.

**Comment by Bro-GunHo** [comment]
same issue
"vimeo/vimeo-api": "^3.0.7"


<br />
<b>Fatal error</b>: Uncaught Vimeo\Exceptions\VimeoUploadException: Unable to create resource. in
/home/dmonster1439/www/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php:608
Stack trace:
#0 /home/dmonster1439/www/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php(338):
Vimeo\Vimeo->perform_upload_tus('/tmp/php7YmIeP', 2925219, Array)
#1 /home/dmonster1439/www/json/procs/proc_content_file.php(99): Vimeo\Vimeo->upload('/tmp/php7YmIeP', Array)
....
#3 {main}
thrown in <b>/home/dmonster1439/www/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php</b> on line <b>608</b><br />

**Comment by HardikKhorasiya09** [comment]
@kailasb 
I am facing the same issue in one of my laravel project.

Version's info:
"php" : ">=7.2.0",
"laravel/framework" :  "^6.12",
"vimeo/vimeo-api" : "3.0.3"

Code: 
$lib = new \Vimeo\Vimeo('vimeo_client_id', 'vimeo_client_secret');
$lib->setToken('vimeo_access_token');
$url = $lib->upload('file for upload', [
    'name' => 'title',
    'description' => 'texts,
    'privacy' => [
        'view' => 'anybody'
    ]
]);

All this working fine in my local environment. But It's no working on my production environment, I get this error "Unable to create resource".

Can any one help me in this..??

**Comment by GeoTimber** [comment]
see https://github.com/vimeo/vimeo.php/issues/266#issuecomment-679085794

**Comment by pluc** [comment]
Do not chmod to 0777 as it gives EVERYONE execution privilege in that folder. Use 0755 to give EVERYONE write access instead if you have to, but in truth you should be giving your web server write permission instead of everyone.

**Comment by Gielovic** [comment]
Finally found a solution for this issue. The client always uses the file-based cache. By default, it writes the cache in the vendor folder (bad idea). 
By setting this environment variable: TUS_CACHE_HOME , you can alter the directory where the cache file is created.
Can be easily set for a docker container f.i.
